require('dotenv').config();

const ROLES = {
  free: { label: 'Free', daily: 1000, price: 0, color: '#9092a4', keys: 1, rate: 60, whitelist: false, priority: 0, support: 'Umum', bonus: 0,
    pros: { en: ['1.000 free credits every day', '1 API key', '60 requests per minute'],
            id: ['1.000 credit gratis setiap hari', '1 API key', '60 request per menit'] },
    cons: { en: ['No IP whitelist', 'No priority queue', 'General support (email)'],
            id: ['Tanpa IP whitelist', 'Tanpa priority queue', 'Support umum (email)'] } },
  vip: { label: 'VIP', daily: 5000, price: 10000, color: '#1bd96a', keys: 3, rate: 120, whitelist: false, priority: 1, support: 'Email', bonus: 2000,
    pros: { en: ['5.000 credits every day', '3 API keys', '120 requests per minute'],
            id: ['5.000 credit setiap hari', '3 API key', '120 request per menit'] },
    cons: { en: ['No IP whitelist', 'No priority queue'],
            id: ['Tanpa IP whitelist', 'Tanpa priority queue'] } },
  gars: { label: 'GARS', daily: 15000, price: 20000, color: '#ffd166', keys: 5, rate: 180, whitelist: true, priority: 2, support: 'Email + WA', bonus: 5000,
    pros: { en: ['15.000 credits every day', '5 API keys', '180 requests per minute', 'IP whitelist', 'Priority queue'],
            id: ['15.000 credit setiap hari', '5 API key', '180 request per menit', 'IP whitelist', 'Priority queue'] },
    cons: { en: ['Support is not dedicated'],
            id: ['Support bukan dedicated'] } },
  vilions: { label: 'VILIONS', daily: 40000, price: 30000, color: '#ff6b9d', keys: 7, rate: 240, whitelist: true, priority: 3, support: 'Email + WA', bonus: 12000,
    pros: { en: ['40.000 credits every day', '7 API keys', '240 requests per minute', 'IP whitelist', 'Priority queue'],
            id: ['40.000 credit setiap hari', '7 API key', '240 request per menit', 'IP whitelist', 'Priority queue'] },
    cons: { en: ['Support is not dedicated'],
            id: ['Support bukan dedicated'] } },
  verus: { label: 'VERUS', daily: 1000000, price: 40000, color: '#b98cff', keys: 10, rate: 300, whitelist: true, priority: 4, support: 'Dedicated (WA + email)', bonus: 300000,
    pros: { en: ['1.000.000 credits every day (resets at 00:00 WIB / UTC+7)', '10 API keys', '300 requests per minute', 'All endpoints + highest priority', 'IP whitelist', 'Top priority queue', 'Dedicated support (WA + email)', '300.000 bonus credits on upgrade'],
            id: ['1.000.000 credit setiap hari (reset 00:00 WIB)', '10 API key', '300 request per menit', 'Semua endpoint + priority tertinggi', 'IP whitelist', 'Priority queue level tertinggi', 'Support dedicated (WA + email)', 'Bonus 300.000 credit saat upgrade'] },
    cons: { en: [], id: [] } },
};

const APIS = [
  {
    id: 'media',
    name: { en: 'Media Downloader', id: 'Media Downloader' },
    desc: { en: 'Download video & audio from YouTube, Instagram, Facebook, TikTok, and X (Twitter).', id: 'Download video & audio dari YouTube, Instagram, Facebook, TikTok, dan X (Twitter).' },
    paths: ['/api/download', '/api/yt', '/api/ig', '/api/fb', '/api/tt', '/api/x', '/api/mp3'],
    status: 'live',
  },
  {
    id: 'music',
    name: { en: 'Music & Lyrics', id: 'Music & Lirik' },
    desc: { en: 'Search songs, grab metadata and lyrics. (In development)', id: 'Cari lagu, ambil metadata, dan lirik. (Dalam pengembangan)' },
    paths: ['/api/music/search'],
    status: 'soon',
  },
  {
    id: 'image',
    name: { en: 'Image Tools', id: 'Image Tools' },
    desc: { en: 'Compress, resize and convert images. (In development)', id: 'Compress, resize, dan konversi gambar. (Dalam pengembangan)' },
    paths: ['/api/image/compress'],
    status: 'soon',
  },
  {
    id: 'text',
    name: { en: 'Text Tools', id: 'Text Tools' },
    desc: { en: 'Formatter, QR generator and text utilities. (In development)', id: 'Formatter, generator QR, dan utilitas teks. (Dalam pengembangan)' },
    paths: ['/api/text/qr'],
    status: 'soon',
  },
];

module.exports = {
  PORT: Number(process.env.PORT) || 3000,
  RATE_LIMIT_PER_MIN: Number(process.env.RATE_LIMIT_PER_MIN) || 60,
  DATABASE_URL: process.env.DATABASE_URL || 'postgres://zunndev:zunndev_dev_pass@localhost:5432/media_api',
  JWT_SECRET: process.env.JWT_SECRET || 'dev_secret_change_me',
  JWT_EXPIRES: process.env.JWT_EXPIRES || '30d',
  COOKIE_NAME: 'md_token',
  FORCE_SECURE: process.env.FORCE_SECURE === 'true',
  QRIS: {
    base: 'https://qris.pw/api',
    key: process.env.QRIS_API_KEY || '',
    secret: process.env.QRIS_API_SECRET || '',
    webhookSecret: process.env.QRIS_WEBHOOK_SECRET || '',
    callbackUrl: process.env.QRIS_CALLBACK_URL || 'https://zunndev.my.id/api/webhook/qris',
    enabled: !!(process.env.QRIS_API_KEY && process.env.QRIS_API_SECRET),
  },
  ADMIN_PATH: process.env.ADMIN_PATH || '',
  ADMIN_EMAILS: (process.env.ADMIN_EMAILS || '').split(',').map((s) => s.trim().toLowerCase()).filter(Boolean),
  ROLES,
  APIS,
};
